config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :journals
  devise_for :users
  get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :journal
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy!

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:title, :body, :published_at, :journal_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1 or /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals or /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to journal_url(@journal), notice: "Journal was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to journal_url(@journal), notice: "Journal was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy!

    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Journal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:title, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/entries/_entry.html.slim
div id="#{dom_id entry}"
  p
    strong Title:
    =< entry.title
  p
    strong Body:
    =< entry.body
  p
    strong Published at:
    =< entry.published_at
  p
    strong Journal:
    =< entry.journal_id

app/views/entries/_form.html.slim
= form_with(model: entry) do |form|
  - if entry.errors.any?
    div style="color: red"
      h2 = "#{pluralize(entry.errors.count, "error")} prohibited this entry from being saved:"
      ul
        - entry.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :body, style: "display: block"
    = form.text_area :body

  div
    = form.label :published_at, style: "display: block"
    = form.datetime_field :published_at

  div
    = form.label :journal_id, style: "display: block"
    = form.text_field :journal_id

  div
    = form.submit

app/views/entries/edit.html.slim
h1 Editing entry

== render "form", entry: @entry

br

div
  => link_to "Show this entry", @entry
  '|
  =< link_to "Back to entries", entries_path

app/views/entries/index.html.slim
p style="color: green" = notice

h1 Entries

#entries
  - @entries.each do |entry|
    == render entry
    p
      = link_to "Show this entry", entry

= link_to "New entry", new_entry_path

app/views/entries/new.html.slim
h1 New entry

== render "form", entry: @entry

br

div
  = link_to "Back to entries", entries_path

app/views/entries/show.html.slim
p style="color: green" = notice

== render @entry

div
  => link_to "Edit this entry", edit_entry_path(@entry)
  '|
  =< link_to "Back to entries", entries_path

  = button_to "Destroy this entry", @entry, method: :delete

app/views/home/index.html.slim
h1 Home#index
p Find me in app/views/home/index.html.slim

app/views/journals/_form.html.slim
= form_with(model: journal) do |form|
  - if journal.errors.any?
    div style="color: red"
      h2 = "#{pluralize(journal.errors.count, "error")} prohibited this journal from being saved:"
      ul
        - journal.errors.each do |error|
          li = error.full_message

  div
    = form.label :title, style: "display: block"
    = form.text_field :title

  div
    = form.label :description, style: "display: block"
    = form.text_area :description

  div
    = form.label :user_id, style: "display: block"
    = form.text_field :user_id

  div
    = form.submit

app/views/journals/_journal.html.slim
div id="#{dom_id journal}"
  p
    strong Title:
    =< journal.title
  p
    strong Description:
    =< journal.description
  p
    strong User:
    =< journal.user_id

app/views/journals/edit.html.slim
h1 Editing journal

== render "form", journal: @journal

br

div
  => link_to "Show this journal", @journal
  '|
  =< link_to "Back to journals", journals_path

app/views/journals/index.html.slim
p style="color: green" = notice

h1 Journals

#journals
  - @journals.each do |journal|
    == render journal
    p
      = link_to "Show this journal", journal

= link_to "New journal", new_journal_path

app/views/journals/new.html.slim
h1 New journal

== render "form", journal: @journal

br

div
  = link_to "Back to journals", journals_path

app/views/journals/show.html.slim
p style="color: green" = notice

== render @journal

div
  => link_to "Edit this journal", edit_journal_path(@journal)
  '|
  =< link_to "Back to journals", journals_path

  = button_to "Destroy this journal", @journal, method: :delete

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Pioneer
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    - if notice.present?
      p.notice
        = notice
    - if alert.present?
      p.alert
        = alert
    = yield